### PR TITLE
Accessibility, grammar, fixing link

### PR DESCRIPTION
**Pull request by sbinlondon**
- Change 'collaboration' to 'cooperation' in FAQs re: issue #90 
- Fix link to Grow app re: issue #62 
- Add :focus styling to buttons and form elements re: issue #89 
- Change button hover and focus styles to make text slightly bigger re: issue #89 
- Change form focus styles to make it more obvious the user is typing in that particular element re: issue #89

### CODE REVIEW

**Review by sima-qian — CHANGES_REQUESTED** [review]
On a design front, I personally dislike the increasing `font-size` when hovering on buttons.

With regard to focus on buttons -- each click of a button navigates you either elsewhere in the page, or to another page, so I can't see the point of having a different design for focussed buttons.

The `font-size` transition on `.form-input-top-line` seems to make no difference?

**Review by sofer — COMMENTED** [review]
I would approve anything that @sbinlondon and @sima-qian agree on.

**Comment by sbinlondon** [comment]
Re: font size, fair enough - just wanted to try it out but happy to take it away.

Re: focus vs hover, we currently have hover styles where the buttons changes. However, if you tab through (like with a screenreader, I'm assuming) then the buttons don't really change style to show that they're able to be clicked. To me, :focus should do the same thing as :hover.

Re: .form-input-top-line I think it seems we should just take the font size change out? 

I propose I'll make changes to take away the font size change but make the :focus and :hover do the same things.

**Comment by sima-qian** [comment]
@sbinlondon Yeah, I'd suggest getting rid of both font-size changes.

You have a point about `focus` styling -- might as well keep it :)

**Pull request closed without merging**
